# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.2&openapi/slurmdbd&openapi/v0.0.39&openapi/dbv0.0.39&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurm_rest.models.v0041_openapi_nodes_resp import V0041OpenapiNodesResp

class TestV0041OpenapiNodesResp(unittest.TestCase):
    """V0041OpenapiNodesResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiNodesResp:
        """Test V0041OpenapiNodesResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiNodesResp`
        """
        model = V0041OpenapiNodesResp()
        if include_optional:
            return V0041OpenapiNodesResp(
                nodes = [
                    slurm_rest.models.v0_0_41_openapi_nodes_resp_nodes_inner.v0_0_41_openapi_nodes_resp_nodes_inner(
                        architecture = '', 
                        burstbuffer_network_address = '', 
                        boards = 56, 
                        boot_time = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cluster_name = '', 
                        cores = 56, 
                        specialized_cores = 56, 
                        cpu_binding = 56, 
                        cpu_load = 56, 
                        free_mem = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cpus = 56, 
                        effective_cpus = 56, 
                        specialized_cpus = '', 
                        energy = slurm_rest.models.v0_0_41_openapi_nodes_resp_nodes_inner_energy.v0_0_41_openapi_nodes_resp_nodes_inner_energy(
                            average_watts = 56, 
                            base_consumed_energy = 56, 
                            consumed_energy = 56, 
                            current_watts = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            previous_consumed_energy = 56, 
                            last_collected = 56, ), 
                        external_sensors = slurm_rest.models.external_sensors.external_sensors(), 
                        extra = '', 
                        power = slurm_rest.models.power.power(), 
                        features = [
                            ''
                            ], 
                        active_features = [
                            ''
                            ], 
                        gpu_spec = '', 
                        gres = '', 
                        gres_drained = '', 
                        gres_used = '', 
                        instance_id = '', 
                        instance_type = '', 
                        last_busy = , 
                        mcs_label = '', 
                        specialized_memory = 56, 
                        name = '', 
                        next_state_after_reboot = [
                            'INVALID'
                            ], 
                        address = '', 
                        hostname = '', 
                        state = [
                            'INVALID'
                            ], 
                        operating_system = '', 
                        owner = '', 
                        partitions = [
                            ''
                            ], 
                        port = 56, 
                        real_memory = 56, 
                        res_cores_per_gpu = 56, 
                        comment = '', 
                        reason = '', 
                        reason_changed_at = , 
                        reason_set_by_user = '', 
                        resume_after = , 
                        reservation = '', 
                        alloc_memory = 56, 
                        alloc_cpus = 56, 
                        alloc_idle_cpus = 56, 
                        tres_used = '', 
                        tres_weighted = 1.337, 
                        slurmd_start_time = , 
                        sockets = 56, 
                        threads = 56, 
                        temporary_disk = 56, 
                        weight = 56, 
                        tres = '', 
                        version = '', )
                    ],
                last_update = slurm_rest.models.v0_0_41_openapi_nodes_resp_last_update.v0_0_41_openapi_nodes_resp_last_update(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                meta = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_meta.v0_0_41_openapi_slurmdbd_jobs_resp_meta(
                    plugin = slurm_rest.models.v0_0_40_openapi_meta_plugin.v0_0_40_openapi_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurm_rest.models.v0_0_40_openapi_meta_client.v0_0_40_openapi_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurm_rest.models.v0_0_40_openapi_meta_slurm.v0_0_40_openapi_meta_slurm(
                        version = slurm_rest.models.v0_0_40_openapi_meta_slurm_version.v0_0_40_openapi_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_errors_inner.v0_0_41_openapi_slurmdbd_jobs_resp_errors_inner(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_warnings_inner.v0_0_41_openapi_slurmdbd_jobs_resp_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0041OpenapiNodesResp(
                nodes = [
                    slurm_rest.models.v0_0_41_openapi_nodes_resp_nodes_inner.v0_0_41_openapi_nodes_resp_nodes_inner(
                        architecture = '', 
                        burstbuffer_network_address = '', 
                        boards = 56, 
                        boot_time = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cluster_name = '', 
                        cores = 56, 
                        specialized_cores = 56, 
                        cpu_binding = 56, 
                        cpu_load = 56, 
                        free_mem = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cpus = 56, 
                        effective_cpus = 56, 
                        specialized_cpus = '', 
                        energy = slurm_rest.models.v0_0_41_openapi_nodes_resp_nodes_inner_energy.v0_0_41_openapi_nodes_resp_nodes_inner_energy(
                            average_watts = 56, 
                            base_consumed_energy = 56, 
                            consumed_energy = 56, 
                            current_watts = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            previous_consumed_energy = 56, 
                            last_collected = 56, ), 
                        external_sensors = slurm_rest.models.external_sensors.external_sensors(), 
                        extra = '', 
                        power = slurm_rest.models.power.power(), 
                        features = [
                            ''
                            ], 
                        active_features = [
                            ''
                            ], 
                        gpu_spec = '', 
                        gres = '', 
                        gres_drained = '', 
                        gres_used = '', 
                        instance_id = '', 
                        instance_type = '', 
                        last_busy = , 
                        mcs_label = '', 
                        specialized_memory = 56, 
                        name = '', 
                        next_state_after_reboot = [
                            'INVALID'
                            ], 
                        address = '', 
                        hostname = '', 
                        state = [
                            'INVALID'
                            ], 
                        operating_system = '', 
                        owner = '', 
                        partitions = [
                            ''
                            ], 
                        port = 56, 
                        real_memory = 56, 
                        res_cores_per_gpu = 56, 
                        comment = '', 
                        reason = '', 
                        reason_changed_at = , 
                        reason_set_by_user = '', 
                        resume_after = , 
                        reservation = '', 
                        alloc_memory = 56, 
                        alloc_cpus = 56, 
                        alloc_idle_cpus = 56, 
                        tres_used = '', 
                        tres_weighted = 1.337, 
                        slurmd_start_time = , 
                        sockets = 56, 
                        threads = 56, 
                        temporary_disk = 56, 
                        weight = 56, 
                        tres = '', 
                        version = '', )
                    ],
                last_update = slurm_rest.models.v0_0_41_openapi_nodes_resp_last_update.v0_0_41_openapi_nodes_resp_last_update(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
        )
        """

    def testV0041OpenapiNodesResp(self):
        """Test V0041OpenapiNodesResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
