# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.2&openapi/slurmdbd&openapi/v0.0.39&openapi/dbv0.0.39&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurm_rest.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time import V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime

class TestV0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime(unittest.TestCase):
    """V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime:
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime`
        """
        model = V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime()
        if include_optional:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime(
                elapsed = 56,
                end = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                start = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                suspended = 56,
                system = slurm_rest.models.v0_0_40_step_time_system.v0_0_40_step_time_system(
                    seconds = 56, 
                    microseconds = 56, ),
                total = slurm_rest.models.v0_0_40_step_time_system.v0_0_40_step_time_system(
                    seconds = 56, 
                    microseconds = 56, ),
                user = slurm_rest.models.v0_0_40_step_time_system.v0_0_40_step_time_system(
                    seconds = 56, 
                    microseconds = 56, )
            )
        else:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime(
        )
        """

    def testV0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime(self):
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
