# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.2&openapi/slurmdbd&openapi/v0.0.39&openapi/dbv0.0.39&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurm_rest.models.v0041_openapi_job_info_resp import V0041OpenapiJobInfoResp

class TestV0041OpenapiJobInfoResp(unittest.TestCase):
    """V0041OpenapiJobInfoResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiJobInfoResp:
        """Test V0041OpenapiJobInfoResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiJobInfoResp`
        """
        model = V0041OpenapiJobInfoResp()
        if include_optional:
            return V0041OpenapiJobInfoResp(
                jobs = [
                    slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner.v0_0_41_openapi_job_info_resp_jobs_inner(
                        account = '', 
                        accrue_time = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        admin_comment = '', 
                        allocating_node = '', 
                        array_job_id = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        array_task_id = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        array_max_tasks = , 
                        array_task_string = '', 
                        association_id = 56, 
                        batch_features = '', 
                        batch_flag = True, 
                        batch_host = '', 
                        flags = [
                            'KILL_INVALID_DEPENDENCY'
                            ], 
                        burst_buffer = '', 
                        burst_buffer_state = '', 
                        cluster = '', 
                        cluster_features = '', 
                        command = '', 
                        comment = '', 
                        container = '', 
                        container_id = '', 
                        contiguous = True, 
                        core_spec = 56, 
                        thread_spec = 56, 
                        cores_per_socket = slurm_rest.models.v0_0_41_job_desc_msg_distribution_plane_size.v0_0_41_job_desc_msg_distribution_plane_size(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        billable_tres = slurm_rest.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_factor.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_factor(
                            set = True, 
                            infinite = True, 
                            number = 1.337, ), 
                        cpus_per_task = slurm_rest.models.v0_0_41_job_desc_msg_distribution_plane_size.v0_0_41_job_desc_msg_distribution_plane_size(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cpu_frequency_minimum = , 
                        cpu_frequency_maximum = , 
                        cpu_frequency_governor = , 
                        cpus_per_tres = '', 
                        cron = '', 
                        deadline = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        delay_boot = , 
                        dependency = '', 
                        derived_exit_code = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code(
                            status = [
                                'INVALID'
                                ], 
                            return_code = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            signal = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal(
                                id = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                name = '', ), ), 
                        eligible_time = , 
                        end_time = , 
                        excluded_nodes = '', 
                        exit_code = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code(), 
                        extra = '', 
                        failed_node = '', 
                        features = '', 
                        federation_origin = '', 
                        federation_siblings_active = '', 
                        federation_siblings_viable = '', 
                        gres_detail = [
                            ''
                            ], 
                        group_id = 56, 
                        group_name = '', 
                        het_job_id = , 
                        het_job_id_set = '', 
                        het_job_offset = , 
                        job_id = 56, 
                        job_resources = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources(
                            select_type = [
                                'CPU'
                                ], 
                            nodes = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes(
                                count = 56, 
                                list = '', 
                                whole = True, 
                                allocation = [
                                    slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner(
                                        index = 56, 
                                        name = '', 
                                        cpus = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_cpus(
                                            count = 56, 
                                            used = 56, ), 
                                        memory = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory(
                                            used = 56, 
                                            allocated = 56, ), 
                                        sockets = [
                                            slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner(
                                                index = 56, 
                                                cores = [
                                                    slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner(
                                                        index = 56, 
                                                        status = [
                                                            'INVALID'
                                                            ], )
                                                    ], )
                                            ], )
                                    ], ), 
                            cpus = 56, 
                            threads_per_core = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        job_size_str = [
                            ''
                            ], 
                        job_state = [
                            'PENDING'
                            ], 
                        last_sched_evaluation = , 
                        licenses = '', 
                        mail_type = [
                            'BEGIN'
                            ], 
                        mail_user = '', 
                        max_cpus = , 
                        max_nodes = , 
                        mcs_label = '', 
                        memory_per_tres = '', 
                        name = '', 
                        network = '', 
                        nodes = '', 
                        nice = 56, 
                        tasks_per_core = , 
                        tasks_per_tres = , 
                        tasks_per_node = , 
                        tasks_per_socket = , 
                        tasks_per_board = , 
                        cpus = , 
                        node_count = , 
                        tasks = , 
                        partition = '', 
                        prefer = '', 
                        memory_per_cpu = , 
                        memory_per_node = , 
                        minimum_cpus_per_node = , 
                        minimum_tmp_disk_per_node = , 
                        power = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_power.v0_0_41_openapi_job_info_resp_jobs_inner_power(), 
                        preempt_time = , 
                        preemptable_time = , 
                        pre_sus_time = , 
                        hold = True, 
                        priority = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_priority.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_priority(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        profile = [
                            'NOT_SET'
                            ], 
                        qos = '', 
                        reboot = True, 
                        required_nodes = '', 
                        minimum_switches = 56, 
                        requeue = True, 
                        resize_time = , 
                        restart_cnt = 56, 
                        resv_name = '', 
                        scheduled_nodes = '', 
                        selinux_context = '', 
                        shared = [
                            'none'
                            ], 
                        exclusive = [
                            'true'
                            ], 
                        oversubscribe = True, 
                        show_flags = [
                            'ALL'
                            ], 
                        sockets_per_board = 56, 
                        sockets_per_node = , 
                        start_time = , 
                        state_description = '', 
                        state_reason = '', 
                        standard_error = '', 
                        standard_input = '', 
                        standard_output = '', 
                        submit_time = , 
                        suspend_time = , 
                        system_comment = '', 
                        time_limit = , 
                        time_minimum = , 
                        threads_per_core = , 
                        tres_bind = '', 
                        tres_freq = '', 
                        tres_per_job = '', 
                        tres_per_node = '', 
                        tres_per_socket = '', 
                        tres_per_task = '', 
                        tres_req_str = '', 
                        tres_alloc_str = '', 
                        user_id = 56, 
                        user_name = '', 
                        maximum_switch_wait_time = 56, 
                        wckey = '', 
                        current_working_directory = '', )
                    ],
                last_backfill = slurm_rest.models.v0_0_41_openapi_job_info_resp_last_backfill.v0_0_41_openapi_job_info_resp_last_backfill(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                last_update = slurm_rest.models.v0_0_41_openapi_job_info_resp_last_update.v0_0_41_openapi_job_info_resp_last_update(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                meta = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_meta.v0_0_41_openapi_slurmdbd_jobs_resp_meta(
                    plugin = slurm_rest.models.v0_0_40_openapi_meta_plugin.v0_0_40_openapi_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurm_rest.models.v0_0_40_openapi_meta_client.v0_0_40_openapi_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurm_rest.models.v0_0_40_openapi_meta_slurm.v0_0_40_openapi_meta_slurm(
                        version = slurm_rest.models.v0_0_40_openapi_meta_slurm_version.v0_0_40_openapi_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_errors_inner.v0_0_41_openapi_slurmdbd_jobs_resp_errors_inner(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_warnings_inner.v0_0_41_openapi_slurmdbd_jobs_resp_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0041OpenapiJobInfoResp(
                jobs = [
                    slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner.v0_0_41_openapi_job_info_resp_jobs_inner(
                        account = '', 
                        accrue_time = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        admin_comment = '', 
                        allocating_node = '', 
                        array_job_id = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        array_task_id = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        array_max_tasks = , 
                        array_task_string = '', 
                        association_id = 56, 
                        batch_features = '', 
                        batch_flag = True, 
                        batch_host = '', 
                        flags = [
                            'KILL_INVALID_DEPENDENCY'
                            ], 
                        burst_buffer = '', 
                        burst_buffer_state = '', 
                        cluster = '', 
                        cluster_features = '', 
                        command = '', 
                        comment = '', 
                        container = '', 
                        container_id = '', 
                        contiguous = True, 
                        core_spec = 56, 
                        thread_spec = 56, 
                        cores_per_socket = slurm_rest.models.v0_0_41_job_desc_msg_distribution_plane_size.v0_0_41_job_desc_msg_distribution_plane_size(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        billable_tres = slurm_rest.models.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_factor.v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_factor(
                            set = True, 
                            infinite = True, 
                            number = 1.337, ), 
                        cpus_per_task = slurm_rest.models.v0_0_41_job_desc_msg_distribution_plane_size.v0_0_41_job_desc_msg_distribution_plane_size(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cpu_frequency_minimum = , 
                        cpu_frequency_maximum = , 
                        cpu_frequency_governor = , 
                        cpus_per_tres = '', 
                        cron = '', 
                        deadline = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        delay_boot = , 
                        dependency = '', 
                        derived_exit_code = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code(
                            status = [
                                'INVALID'
                                ], 
                            return_code = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            signal = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal(
                                id = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                name = '', ), ), 
                        eligible_time = , 
                        end_time = , 
                        excluded_nodes = '', 
                        exit_code = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code(), 
                        extra = '', 
                        failed_node = '', 
                        features = '', 
                        federation_origin = '', 
                        federation_siblings_active = '', 
                        federation_siblings_viable = '', 
                        gres_detail = [
                            ''
                            ], 
                        group_id = 56, 
                        group_name = '', 
                        het_job_id = , 
                        het_job_id_set = '', 
                        het_job_offset = , 
                        job_id = 56, 
                        job_resources = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources(
                            select_type = [
                                'CPU'
                                ], 
                            nodes = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes(
                                count = 56, 
                                list = '', 
                                whole = True, 
                                allocation = [
                                    slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner(
                                        index = 56, 
                                        name = '', 
                                        cpus = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_cpus.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_cpus(
                                            count = 56, 
                                            used = 56, ), 
                                        memory = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory(
                                            used = 56, 
                                            allocated = 56, ), 
                                        sockets = [
                                            slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner(
                                                index = 56, 
                                                cores = [
                                                    slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_sockets_inner_cores_inner(
                                                        index = 56, 
                                                        status = [
                                                            'INVALID'
                                                            ], )
                                                    ], )
                                            ], )
                                    ], ), 
                            cpus = 56, 
                            threads_per_core = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core.v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_threads_per_core(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        job_size_str = [
                            ''
                            ], 
                        job_state = [
                            'PENDING'
                            ], 
                        last_sched_evaluation = , 
                        licenses = '', 
                        mail_type = [
                            'BEGIN'
                            ], 
                        mail_user = '', 
                        max_cpus = , 
                        max_nodes = , 
                        mcs_label = '', 
                        memory_per_tres = '', 
                        name = '', 
                        network = '', 
                        nodes = '', 
                        nice = 56, 
                        tasks_per_core = , 
                        tasks_per_tres = , 
                        tasks_per_node = , 
                        tasks_per_socket = , 
                        tasks_per_board = , 
                        cpus = , 
                        node_count = , 
                        tasks = , 
                        partition = '', 
                        prefer = '', 
                        memory_per_cpu = , 
                        memory_per_node = , 
                        minimum_cpus_per_node = , 
                        minimum_tmp_disk_per_node = , 
                        power = slurm_rest.models.v0_0_41_openapi_job_info_resp_jobs_inner_power.v0_0_41_openapi_job_info_resp_jobs_inner_power(), 
                        preempt_time = , 
                        preemptable_time = , 
                        pre_sus_time = , 
                        hold = True, 
                        priority = slurm_rest.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_priority.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_priority(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        profile = [
                            'NOT_SET'
                            ], 
                        qos = '', 
                        reboot = True, 
                        required_nodes = '', 
                        minimum_switches = 56, 
                        requeue = True, 
                        resize_time = , 
                        restart_cnt = 56, 
                        resv_name = '', 
                        scheduled_nodes = '', 
                        selinux_context = '', 
                        shared = [
                            'none'
                            ], 
                        exclusive = [
                            'true'
                            ], 
                        oversubscribe = True, 
                        show_flags = [
                            'ALL'
                            ], 
                        sockets_per_board = 56, 
                        sockets_per_node = , 
                        start_time = , 
                        state_description = '', 
                        state_reason = '', 
                        standard_error = '', 
                        standard_input = '', 
                        standard_output = '', 
                        submit_time = , 
                        suspend_time = , 
                        system_comment = '', 
                        time_limit = , 
                        time_minimum = , 
                        threads_per_core = , 
                        tres_bind = '', 
                        tres_freq = '', 
                        tres_per_job = '', 
                        tres_per_node = '', 
                        tres_per_socket = '', 
                        tres_per_task = '', 
                        tres_req_str = '', 
                        tres_alloc_str = '', 
                        user_id = 56, 
                        user_name = '', 
                        maximum_switch_wait_time = 56, 
                        wckey = '', 
                        current_working_directory = '', )
                    ],
                last_backfill = slurm_rest.models.v0_0_41_openapi_job_info_resp_last_backfill.v0_0_41_openapi_job_info_resp_last_backfill(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                last_update = slurm_rest.models.v0_0_41_openapi_job_info_resp_last_update.v0_0_41_openapi_job_info_resp_last_update(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
        )
        """

    def testV0041OpenapiJobInfoResp(self):
        """Test V0041OpenapiJobInfoResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
